name: Vérifier et régénérer .meta.js en cas de modification de .user.js ou de merge.
#permet de génerer automatiquement le fichier meta à partir du fichier userjs.
#.github/workflows/generate-meta.yml


on:
  push:
    paths:
      - JVCForumRollback.user.js
  workflow_dispatch:

jobs:
  extract_meta:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Extraire uniquement l'en-tête UserScript
        run: |
          # Vider le fichier pour éviter l’accumulation
          : > JVCForumRollback.meta.js

          # Copier les lignes de l'en-tête jusqu'à ==/UserScript==
          awk '/==\/UserScript==/ {print; exit} {print}' JVCForumRollback.user.js >> JVCForumRollback.meta.js

      - name: Commit et push si changement
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add JVCForumRollback.meta.js
          # Ne commit ET ne push que si le fichier a réellement changé
          if ! git diff --cached --quiet; then
            git commit -m "Auto: mise à jour de .meta.js"
            git push
          fi
